<?php

/**
 * Paystack Magento2 Module using \Magento\Payment\Model\Method\AbstractMethod
 * Copyright (C) 2019 Paystack.com
 *
 * This file is part of Pstk/Paystack.
 *
 * Pstk/Paystack is free software => you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http =>//www.gnu.org/licenses/>.
 */

namespace Pstk\Paystack\Controller\Payment;

use Magento\Sales\Api\Data\OrderInterface;
use Pstk\Paystack\Gateway\Validator\TransactionValidator;

class Webhook extends AbstractPaystackStandard
{
    /**
     * How long after a transaction's paid_at/created_at an order-not-found result
     * stays transient (503, Paystack retries). Beyond this window it becomes
     * permanent (200): most charge.success events with no matching order will
     * never get one (Payment Pages, dashboard charges, subscription renewals,
     * another integration on the same Paystack account), and 503-ing those for
     * Paystack's full ~72h retry budget is what makes Paystack back off or
     * disable the endpoint, losing legitimate confirmations elsewhere.
     */
    private const ORDER_LOOKUP_RETRY_WINDOW_SECONDS = 900;

    public function execute() {
        $result = $this->resultFactory->create(\Magento\Framework\Controller\ResultFactory::TYPE_RAW);
        try {

            // Retrieve the request's body and parse it as JSON
            $rawBody = $this->request->getContent();

            $this->logger->info("Paystack Webhook: received request");

            // Validate webhook signature
            $signature = $this->request->getHeader('X-Paystack-Signature') ?: '';
            if (!$signature || !$this->paystackClient->validateWebhookSignature($rawBody, $signature)) {
                $this->logger->warning("Paystack Webhook: signature validation failed");
                return $this->respond($result, 401, "auth failed");
            }

            $this->logger->info("Paystack Webhook: signature valid");

            $event = json_decode($rawBody);
            if (!$event) {
                // Malformed JSON cannot be fixed by a retry — permanent, not 503.
                return $this->respond($result, 200, "invalid payload");
            }

            $eventType = $event->event ?? null;
            $this->logger->info("Paystack Webhook: event type = " . ($eventType ?? 'unknown'));

            switch ($eventType) {
                case 'charge.success':
                    $eventStatus = $event->data->status ?? null;
                    if ('success' === $eventStatus) {
                        $eventReference = $event->data->reference ?? null;
                        if (!is_string($eventReference) || $eventReference === '') {
                            // A signed payload with no reference to verify cannot be
                            // fixed by a retry — Paystack will resend the same body.
                            $this->logger->warning("Paystack Webhook: signed payload missing data.reference");
                            return $this->respond($result, 200, "invalid payload");
                        }

                        $transactionDetails = $this->paystackClient->verifyTransaction($eventReference);

                        $reference = $transactionDetails->data->reference ?? null;
                        if (!is_string($reference) || $reference === '') {
                            // The verify response itself is unreadable — that is the
                            // gateway's answer, not our payload, so a retry may get a
                            // readable one. Transient, matching REASON_MALFORMED below.
                            $this->logger->warning("Paystack Webhook: verify response missing data.reference", ['event_reference' => $eventReference]);
                            return $this->respond($result, 503, "unverified");
                        }

                        $this->logger->info("Paystack Webhook: verified transaction", ['reference' => $reference]);

                        $order = $this->orderInterface->loadByIncrementId($reference);

                        // In popup mode, reference is generated by Paystack and we provided quoteId instead
                        if ((!$order || !$order->getId()) && isset($event->data->metadata->quoteId)) {
                            $this->logger->info("Paystack Webhook: order not found by reference, searching by quoteId", ['quoteId' => $event->data->metadata->quoteId]);
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $searchCriteriaBuilder = $objectManager->create('Magento\Framework\Api\SearchCriteriaBuilder');
                            $searchCriteria = $searchCriteriaBuilder->addFilter('quote_id', $event->data->metadata->quoteId, 'eq')->create();
                            $items = $this->orderRepository->getList($searchCriteria);
                            if ($items->getTotalCount() == 1) {
                                $order = $items->getFirstItem();
                            }
                        }

                        if ($order && $order->getId()) {
                            [$code, $body] = $this->resolveSettlement($transactionDetails, $order, $reference);
                            return $this->respond($result, $code, $body);
                        }

                        [$code, $body] = $this->resolveOrderNotFound($transactionDetails, $reference);
                        return $this->respond($result, $code, $body);
                    }
                    break;
            }
        } catch (\Throwable $exc) {
            // \Throwable, not \Exception: a TypeError (e.g. verifyTransaction()'s
            // non-nullable param) must not escape uncaught. Default transient so
            // Paystack retries; the message stays out of the response body since
            // it can carry curl_error()/gateway detail.
            $this->logger->error("Paystack Webhook: exception", ['error' => $exc->getMessage()]);
            return $this->respond($result, 503, "error");
        }

        // Every event type this switch does not handle, and a charge.success
        // whose payload status is not itself "success", falls through to here.
        // Neither is an error — Paystack sends many event types this endpoint
        // does not act on — so it is permanently accepted (200), never retried.
        return $this->respond($result, 200, "ignored");
    }

    /**
     * Sets $result's code/body and returns it. Mutates the one Raw instance
     * execute() created rather than building a new result, so every exit
     * point shares it.
     *
     * @param \Magento\Framework\Controller\Result\Raw $result
     * @param int $code
     * @param string $body
     * @return \Magento\Framework\Controller\Result\Raw
     */
    private function respond($result, int $code, string $body)
    {
        $result->setHttpResponseCode($code);
        $result->setContents($body);
        return $result;
    }

    /**
     * Decides the webhook response for a matched order: re-verifies settlement,
     * dispatches and logs the surplus on success, records merchant-visible
     * history on rejection. Needs no result object — a pure decision function.
     *
     * @param object $transactionDetails Full envelope PaystackApiClient::verifyTransaction() returns
     * @param OrderInterface $order
     * @param string $reference
     * @return array{0: int, 1: string}
     */
    private function resolveSettlement(object $transactionDetails, OrderInterface $order, string $reference): array
    {
        // The webhook payload's own status only got us this far; the
        // re-verified response is the trustworthy statement of what
        // actually happened to the money — nothing may advance the
        // order until it settles this order, in this currency, for at
        // least this amount.
        $reason = $this->transactionValidator->settlementFailureReason($transactionDetails, $order);
        $expectedSubunits = $this->transactionValidator->expectedSubunits($order);

        if (null === $reason) {
            $this->logger->info("Paystack Webhook: order found, dispatching verify event", [
                'order_id' => $order->getIncrementId(),
                'current_status' => $order->getStatus(),
            ]);

            // Only reported to Paystack's plugin tracker once the settlement
            // gate has actually passed — logging it earlier told Paystack a
            // charge succeeded even for rejected settlements.
            $this->paystackClient->logTransactionSuccess($reference, $this->configProvider->getPublicKey());

            if ($this->transactionValidator->isOverpayment($transactionDetails, $order)) {
                // isOverpayment() returning true guarantees paidSubunits() is non-null.
                $paidAmount = $this->transactionValidator->paidSubunits($transactionDetails);
                $this->recordHistory(
                    $order,
                    $reference,
                    'overpaid',
                    sprintf(
                        'Paystack: payment overpaid — paid %d, expected %d, reference %s',
                        $paidAmount,
                        $expectedSubunits,
                        $reference
                    )
                );
            }

            // dispatch the `payment_verify_after` event to update the order status
            $this->eventManager->dispatch('paystack_payment_verify_after', [
                "paystack_order" => $order,
            ]);

            return [200, "success"];
        }

        $this->logger->warning("Paystack Webhook: settlement check failed", [
            'reason' => $reason,
            'order_id' => $order->getIncrementId(),
        ]);

        if (TransactionValidator::REASON_IN_FLIGHT === $reason) {
            // Bank transfer / USSD still settling — the only reason that
            // genuinely resolves on its own. Retry unconditionally.
            return [503, "pending"];
        }

        // See TransactionValidator::PERMANENT_FOR_WEBHOOK for which reasons
        // are safe to report permanent.
        $isPermanentReason = $this->transactionValidator->isPermanentForWebhook($reason);

        // Signature-verified path: every real charge fires this webhook, so
        // this is the merchant's only visibility into "money moved but the
        // order did not advance". Dedupes via historyMarker() so a transient
        // reason retried for up to 72h doesn't append a comment every time.
        $paidAmount = $this->transactionValidator->paidSubunits($transactionDetails) ?? 'unknown';
        $paidCurrency = $transactionDetails->data->currency ?? 'unknown';
        $this->recordHistory(
            $order,
            $reference,
            $reason,
            sprintf(
                'Paystack: payment %s — %s: paid %s %s, expected %s %s, reference %s',
                $isPermanentReason ? 'rejected' : 'not applied (retry pending)',
                $reason,
                $paidAmount,
                $paidCurrency,
                $expectedSubunits,
                $order->getOrderCurrencyCode(),
                $reference
            )
        );

        if ($isPermanentReason) {
            return [200, "rejected"];
        }

        // WRONG_METHOD/MALFORMED/unrecognised reasons get the same recency
        // bound as order-not-found below: keep retrying while the failure
        // could still be a not-yet-hydrated relation or an unreadable
        // response, stop paying the retry cost once it no longer plausibly is.
        if ($this->isRecentTransaction($transactionDetails)) {
            return [503, "unverified"];
        }

        return [200, "unverified"];
    }

    /**
     * Decides the webhook response when no order matches a verified reference.
     *
     * @param object $transactionDetails Full envelope PaystackApiClient::verifyTransaction() returns
     * @param string $reference
     * @return array{0: int, 1: string}
     */
    private function resolveOrderNotFound(object $transactionDetails, string $reference): array
    {
        $this->logger->warning("Paystack Webhook: order not found for reference " . $reference);

        if ($this->isRecentTransaction($transactionDetails)) {
            // Recent transaction, no matching order yet — could be a
            // genuine order-save race; let Paystack retry within the window.
            return [503, "order not found"];
        }

        // Old transaction, still no order: very likely this will never
        // have a Magento order at all (see the class constant's comment).
        $this->logger->warning("Paystack Webhook: order not found and transaction not recent, treating as permanent", ['reference' => $reference]);
        return [200, "order not found"];
    }

    /**
     * The stable (reference, reason) marker embedded in a history comment —
     * the single definition recordHistory() writes and dedupes against, so
     * the human-readable prose around it can be reworded without breaking
     * dedupe.
     *
     * @param string $reference
     * @param string $reasonKey
     * @return string
     */
    private function historyMarker(string $reference, string $reasonKey): string
    {
        return sprintf('[paystack:%s:%s]', $reference, $reasonKey);
    }

    /**
     * Writes a merchant-visible order-history comment, but only once per
     * (reference, reason) pair: WRONG_METHOD and MALFORMED are transient (503)
     * and Paystack's ~72h retry window would otherwise append a near-identical
     * comment on every retry of the same rejection. A failed write, and a
     * failed lookup of the existing history, must not turn a rejection/
     * overpayment note into a 503 retry storm — log and continue.
     *
     * @param OrderInterface $order
     * @param string $reference
     * @param string $reasonKey
     * @param string $comment
     * @return void
     */
    private function recordHistory(OrderInterface $order, string $reference, string $reasonKey, string $comment): void
    {
        $marker = $this->historyMarker($reference, $reasonKey);
        try {
            foreach ($order->getStatusHistories() ?? [] as $history) {
                $existingComment = $history->getComment() ?? '';
                if (strpos($existingComment, $marker) !== false) {
                    // Already recorded for this (reference, reason) pair — this is a
                    // retry of an event we already wrote a comment for.
                    return;
                }
            }

            $order->addStatusToHistory($order->getStatus(), $comment . ' ' . $marker);
            $this->orderRepository->save($order);
        } catch (\Throwable $exc) {
            // A failed history write must not turn an already-decided
            // rejection into a 503 retry that can never fix it — log and continue.
            $this->logger->error("Paystack Webhook: failed to write order history", ['error' => $exc->getMessage()]);
        }
    }

    /**
     * Whether a verify response's transaction is recent enough that "no matching
     * order" should still be treated as transient. Reads data.paid_at, falling back
     * to data.created_at, then to "treat as recent" if neither is present or parses
     * — a missing/unreadable timestamp must not permanently strand a genuine payment.
     *
     * @param object $transactionDetails Full envelope PaystackApiClient::verifyTransaction() returns
     * @return bool
     */
    private function isRecentTransaction(object $transactionDetails): bool
    {
        $data = $transactionDetails->data ?? null;
        $timestamp = (is_object($data) ? ($data->paid_at ?? $data->created_at ?? null) : null);
        if (!is_string($timestamp) || $timestamp === '') {
            return true;
        }

        $parsed = strtotime($timestamp);
        if ($parsed === false) {
            return true;
        }

        return (time() - $parsed) <= self::ORDER_LOOKUP_RETRY_WINDOW_SECONDS;
    }
}
